server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dheeraj-Khakre/config-server-rating-app
          clone-on-start: true